easy_admin:
    entities:
        Post:
            class: App\Entity\Post
        Category:
            class: App\Entity\Category
            new:
                fields: ['name']
        User:
            class: App\Entity\User
